#!/Users/ddeemer/.pyenv/versions/3.9.0/bin/python
from GeneralTools.Utilities.command_line import find_executable
import json
import os
import sys


essential_params = ['executables', 'run']


# Step 0: Parse through the config file and make sure everything is
# A-ok
def parse_config(config):
    '''
    '''
    with open('pipeline-config.json') as f:
        data = json.load(f)
    # Make sure essentials are all there:
    try:
        execs = data['executables']
        runs = data['run']
    except KeyError:
        print("When parsing essential params, one or more were not included.")
        print(f"Essential params:\n{essential_params}\n")
    # Next, parse optional commands


parse_config('pipeline-config.json')
# Step 1: Make sure that the executables are found in the
# current environment. If not, jump into an environment


def search_executables(executable):
    return find_executable(executable)



# val = data['poop']

# for val in execs:
#     a = main(val)
#     print(a)

# if __name__ == '__main__':
#     print(main(sys.argv[1]))
